name: tests
on:
  push:
    branches:
    - main
  pull_request: []
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.3
      id: go

    - name: Check out source
      uses: actions/checkout@v1

    - name: Set-Up SQLite
      run: make internal/sqlite/sqlite3.c

    - name: Vet
      run: make vet

    - name: Test-Cover
      run: make test-cover
    
    - name: Upload coverage
      uses: codecov/codecov-action@v1
